const playList = [
  "https://jetsetradio.live/radio/stations/lofi/90sFlav - Balmy.mp3",
  "https://jetsetradio.live/radio/stations/lofi/90sFlav - Call Me.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Adam Kay - Rehab (Instrumental).mp3",
  "https://jetsetradio.live/radio/stations/lofi/Aekasora - almost there.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Altitude - lake serene.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Aso - Coffee.mp3",
  "https://jetsetradio.live/radio/stations/lofi/blvknight - december.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Bknapp - Game Over (Super Mario Lofi).mp3",
  "https://jetsetradio.live/radio/stations/lofi/BurBank - A Beautiful Name.mp3",
  "https://jetsetradio.live/radio/stations/lofi/cat naps - hazy dreams.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Burbank - The Shadow Of Your Smile.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Burbank - Moonlights.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Afternoon - spring (w park bird).mp3",
  "https://jetsetradio.live/radio/stations/lofi/App - My First.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Jinsang - Flow.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Jinsang - slumpin.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Jinsang - Bright.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Kudasai & L0v.ly - Paradise.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Kudosai & two.sleepy - fortune.mp3",
  "https://jetsetradio.live/radio/stations/lofi/L'indecis - Le Sud.mp3",
  "https://jetsetradio.live/radio/stations/lofi/L'indecis - Soulful.mp3",
  "https://jetsetradio.live/radio/stations/lofi/LAKEY INSPIRED - Chill Day.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Lee - I Need A girl.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Letskey - Memories.mp3",
  "https://jetsetradio.live/radio/stations/lofi/Lily Potter - Oblivion.mp3",
  "https://jetsetradio.live/radio/stations/lofi/LoFi - Forever.mp3",
  "https://jetsetradio.live/radio/stations/lofi/LoFi - Hold Me.mp3",
  "https://jetsetradio.live/radio/stations/lofi/LoFi - I Am Sad In My Room Once Again.mp3",
  "https://jetsetradio.live/radio/stations/lofi/LoFi - MoonLight.mp3",
];

export default playList;
